// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5mM7lOIdBM5t1m9EWYwu8etReevhZbw',
    appId: '1:611996652112:android:02d166978342a0a6d8b755',
    messagingSenderId: '611996652112',
    projectId: 'mynotes-heshanthaka',
    storageBucket: 'mynotes-heshanthaka.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkEsek1M2Zc3bXgeUe_yxSz4ObF3Hda0',
    appId: '1:611996652112:ios:6b93c82331839fd8d8b755',
    messagingSenderId: '611996652112',
    projectId: 'mynotes-heshanthaka',
    storageBucket: 'mynotes-heshanthaka.appspot.com',
    iosClientId: '611996652112-krueiv5b4pr9ve004ask8b7ta2ktmbjj.apps.googleusercontent.com',
    iosBundleId: 'com.heshanthaka',
  );
}
